### ISSUE TITLE
latest versions not available via composer

### ISSUE THREAD

**Issue by smcphill** [gabordemooij/redbean#261]
I'm using composer to manage package dependencies, and wanted to update to v3.4.3. I updated my composer.json accordingly and ran the update, but composer didn't find anything newer than v3.4.2 for redbean. I've copied the relevant composer.json snippet below.

Any ideas?

``` yaml
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/gabordemooij/redbean"
    }
  ],
  "require": {
    "gabordemooij/redbean": ">=3.4.2"
  }

```
