### ISSUE TITLE
Website dark mode (CSS inside!)

### ISSUE THREAD

**Issue by alystair** [gabordemooij/redbean#790]
Disliked being blinded at night, so I put together a custom style for redbeanphp.com that:

- allows you to modify your base CSS as you see fit and the dark version will adapt along with it (mostly) due to my personal trick of combined use of filter inversion & hue rotation.
- uses a new media selector that enables dark mode only on systems that prefer dark mode

If you dislike the `<code>` block colors, simply add `code { filter:hue-rotate( 0deg ); }` and tweek degrees until happy. Same goes for other base elements such as `<a>` etc etc.

```css
@media (prefers-color-scheme:dark) {
    .content { filter:hue-rotate(60deg) invert(); }
    .content h1::after, .content h2::after {filter:invert() hue-rotate(-60deg); }
    .top ul {z-index:1; background:#5f1207}
    .footblock {filter:hue-rotate(-60deg) invert(); background:#333}
    .logos a { background-color:#000 }
    .note { filter:brightness(.6) invert() hue-rotate(-60deg); }
    .content img,
    .content input[type="image"] { filter:brightness(.8) hue-rotate(-60deg)  invert(); }
}
```
![image](https://user-images.githubusercontent.com/159109/76691708-34dd5e00-6624-11ea-8942-f52e305037ab.png)

Enjoy! 🦉
